// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adewepeqvapvqsngacdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZXdlcGVxdmFwdnFzbmdhY2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5ODc2NDcsImV4cCI6MjA1NjU2MzY0N30.e8WjAI2tVNYu7oB19jD-WwrMGu4G5gQdebgXsOCoSQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);